version: "3.8"
services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DEBUG_REMINDERS=${DEBUG_REMINDERS}
    volumes:
      - ./bot.db:/app/bot.db  # опционально, если вы хотите хранить базу на хосте
    restart: always
